P2P/urls.py
from django.urls import include, path
from .views import P2P,P2P_send,P2P_receive

urlpatterns = [

     
     path('', P2P, name='Duka'),
     path('send', P2P_send, name='send'),
     path('receive', P2P_receive, name='send')
]

accounts/urls.py
from django.urls import path
from . import views
from .views import UserRegistrationView, LogoutView, UserLoginView,Sure_kuleft


app_name = 'accounts'

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="user_login"),
    path("out", LogoutView.as_view(), name="optout"),
    path("logout/", Sure_kuleft, name="user_logout"),
    path( "register/", UserRegistrationView.as_view(), name="user_registration"),
    #path('index', views.index, name='index'),
    path('settings', views.settings, name='settings'),
    path('upload', views.upload, name='upload'),
    #path('follow', views.follow, name='follow'),
    #path('search', views.search, name='search'),
    #path('profile/<str:pk>', views.profile, name='profile'),
    #path('like-post', views.like_post, name='like-post'),
]

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('index', views.index, name='index'),
    path('settings', views.settings, name='settings'),
    path('upload', views.upload, name='upload'),
    path('follow', views.follow, name='follow'),
    path('search', views.search, name='search'),
    path('profile/<str:pk>', views.profile, name='profile'),
    path('like-post', views.like_post, name='like-post'),
]

transactions/urls.py
from django.urls import path

from .views import DepositMoneyView, WithdrawMoneyView, TransactionRepostView, eshopCart , MboaCoins


app_name = 'transactions'


urlpatterns = [
    path("deposit/", DepositMoneyView.as_view(), name="deposit_money"),
    path("report/", TransactionRepostView.as_view(), name="transaction_report"),
    path("withdraw/", WithdrawMoneyView.as_view(), name="withdraw_money"),
    path("mboapay/", eshopCart.as_view(), name="eshopcart"),
    path("mboaCoins/", MboaCoins.as_view(), name="eshopcart"),
]

core/models.py
from django.db import models
import uuid
from datetime import datetime
from django.conf import settings

# Create your views here.

User = settings.AUTH_USER_MODEL


# Create your models here.
class Profile(models.Model):
    user = User
    id_user = models.IntegerField()
    bio = models.TextField(blank=True)
    profileimg = models.ImageField(upload_to='profile_images', default='blank-profile-picture.png')
    location = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.user

class Post(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    user = models.CharField(max_length=100)
    image = models.ImageField(upload_to='post_images')
    caption = models.TextField()
    created_at = models.DateTimeField(default=datetime.now)
    no_of_likes = models.IntegerField(default=0)

    def __str__(self):
        return self.user

class LikePost(models.Model):
    post_id = models.CharField(max_length=500)
    username = models.CharField(max_length=100)

    def __str__(self):
        return self.username

class FollowersCount(models.Model):
    follower = models.CharField(max_length=100)
    user = models.CharField(max_length=100)

    def __str__(self):
        return self.user

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import  auth
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Profile, Post, LikePost, FollowersCount
from itertools import chain
import random
from accounts.models import User,UserAddress

# Create your views here.


@login_required(login_url='signin')
def index(request):
    user_object = User.objects.get(username=request.user.username)
    user_profile = Profile.objects.get(user=user_object)

    user_following_list = []
    feed = []

    user_following = FollowersCount.objects.filter(follower=request.user.username)

    for users in user_following:
        user_following_list.append(users.user)

    for usernames in user_following_list:
        feed_lists = Post.objects.filter(user=usernames)
        feed.append(feed_lists)

    feed_list = list(chain(*feed))

    # user suggestion starts
    all_users = User.objects.all()
    user_following_all = []

    for user in user_following:
        user_list = User.objects.get(username=user.user)
        user_following_all.append(user_list)
    
    new_suggestions_list = [x for x in list(all_users) if (x not in list(user_following_all))]
    current_user = User.objects.filter(username=request.user.username)
    final_suggestions_list = [x for x in list(new_suggestions_list) if ( x not in list(current_user))]
    random.shuffle(final_suggestions_list)

    username_profile = []
    username_profile_list = []

    for users in final_suggestions_list:
        username_profile.append(users.id)

    for ids in username_profile:
        profile_lists = Profile.objects.filter(id_user=ids)
        username_profile_list.append(profile_lists)

    suggestions_username_profile_list = list(chain(*username_profile_list))


    return render(request, 'blog/index.html', {'user_profile': user_profile, 'posts':feed_list, 'suggestions_username_profile_list': suggestions_username_profile_list[:4]})

@login_required(login_url='/accounts/login')
def upload(request):

    if request.method == 'POST':
        user = request.user.username
        image = request.FILES.get('image_upload')
        caption = request.POST['caption']

        new_post = Post.objects.create(user=user, image=image, caption=caption)
        new_post.save()

        return redirect('blog/profile.html')
    else:
        return redirect('blog/setting.html')

@login_required(login_url='/accounts/login')
def search(request):
    user_object = UserAddress.objects.get(user=request.user)
    user_profile = Profile.user(user=user_object)

    if request.method == 'POST':
        username = request.POST['username']
        username_object = User.objects.filter(username__icontains=username)

        username_profile = []
        username_profile_list = []

        for users in username_object:
            username_profile.append(users.id)

        for ids in username_profile:
            profile_lists = Profile.objects.filter(id_user=ids)
            username_profile_list.append(profile_lists)
        
        username_profile_list = list(chain(*username_profile_list))
    return render(request, 'blog/search.html', {'user_profile': user_profile, 'username_profile_list': username_profile_list})

@login_required(login_url='/accounts/login')
def like_post(request):
    username = request.user.username
    post_id = request.GET.get('post_id')

    post = Post.objects.get(id=post_id)

    like_filter = LikePost.objects.filter(post_id=post_id, username=username).first()

    if like_filter == None:
        new_like = LikePost.objects.create(post_id=post_id, username=username)
        new_like.save()
        post.no_of_likes = post.no_of_likes+1
        post.save()
        return redirect('/')
    else:
        like_filter.delete()
        post.no_of_likes = post.no_of_likes-1
        post.save()
        return redirect('/')

@login_required(login_url='/accounts/login')
def profile(request, pk):
    user_object = User.objects.get(username=pk)
    user_profile = Profile.objects.get(user=user_object)
    user_posts = Post.objects.filter(user=pk)
    user_post_length = len(user_posts)

    follower = request.user.username
    user = pk

    if FollowersCount.objects.filter(follower=follower, user=user).first():
        button_text = 'Unfollow'
    else:
        button_text = 'Follow'

    user_followers = len(FollowersCount.objects.filter(user=pk))
    user_following = len(FollowersCount.objects.filter(follower=pk))

    context = {
        'user_object': user_object,
        'user_profile': user_profile,
        'user_posts': user_posts,
        'user_post_length': user_post_length,
        'button_text': button_text,
        'user_followers': user_followers,
        'user_following': user_following,
    }
    return render(request, 'blog/profile.html', context)

@login_required(login_url='/accounts/login')
def follow(request):
    if request.method == 'POST':
        follower = request.POST['follower']
        user = request.POST['user']

        if FollowersCount.objects.filter(follower=follower, user=user).first():
            delete_follower = FollowersCount.objects.get(follower=follower, user=user)
            delete_follower.delete()
            return redirect('/profile/'+user)
        else:
            new_follower = FollowersCount.objects.create(follower=follower, user=user)
            new_follower.save()
            return redirect('/profile/'+user)
    else:
        return redirect('/')

@login_required(login_url='/accounts/login')
def settings(request):
    user_profile = Profile.objects.get(user=request.user)

    if request.method == 'POST':
        
        if request.FILES.get('image') == None:
            image = user_profile.profileimg
            bio = request.POST['bio']
            location = request.POST['location']

            user_profile.profileimg = image
            user_profile.bio = bio
            user_profile.location = location
            user_profile.save()
        if request.FILES.get('image') != None:
            image = request.FILES.get('image')
            bio = request.POST['bio']
            location = request.POST['location']

            user_profile.profileimg = image
            user_profile.bio = bio
            user_profile.location = location
            user_profile.save()
        
        return redirect('settings')
    return render(request, 'blog/setting.html', {'user_profile': user_profile})

templates/core/MboaCoins.html
{% load static %}

      <div style="width:100%;margin-bottom:20px; margin-right: 10px; height:50vh;" class="bty">

<header style="height:2vh;  box-shadow: 10px 0px 34px 50px #fff;background-color:#fff;"> </header>
{% if request.user.is_authenticated %}
<form action="{% url 'stk' %}" method="POST" >
                                                             {% csrf_token %}
                                                             <input type="text" id="phone_number"  hidden  readonly value="0{{user.address.postal_code}}" name="phone_number" placeholder="phone number"
                                                              class="btn form-control" required autofocus    style="font-family:Comic Sans Mn;font-size:24px;text-align:center; margin-top:5px;border-radius:10px;height:7vh; width:100%; "><br>
                                                             <input type="number" id="amount" hidden  readonly value="{{ user.account.balance }}" required name="amount" class=" btn form-control" placeholder="Amount " style="font-family:Comic Sans Mn;font-size:24px;text-align:center; height:7vh;margin-top:20px; margin-bottom:70px;border-radius:10px; width:100%;">
             <button style="border-radius:20px; padding:2px;margin-left:10%;margin-top:80vh;width:60%; " type="submit" class="btn btn-md my-0 p">
              Buy |  <img style="width:50px; font-size:40%;  height:40px;"   src="{% static '/img/mpesa.png'%}">
            </button>
                   </form>


 {% else %}
            <div>
                <a href="/Deposit" class="btn mr-2 inline-block font-medium text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-gray-800 hover:bg-white mt-4 lg:mt-0">Buy  | <img style="width:50px; font-size:40%;  height:40px;"   src="{% static '/img/mpesa.png'%}">
                </a></div>
{% endif %}
<form>
    <div style="display:flex; flex-direction:row; margin-top:20px;">
<div class="bty" style="background-color:#008800; width:85px;height:40px;margin-right:-20;">
    <p>Ksh.</p>
    </div>
        <input   style="color: #001100;text-align:center; width:90%;height:40px;margin-right:40% background-color:transparent;" class="bty shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="amount" id="amount" type="number" required placeholder=" Enter Amount ">


    </div></form><br>
<p style="font-size:80%;">Mboa Coins to Receive...</p>

             <div class="btn" style="border-radius:7px;width:100%;height:50px;text-align:center;">

             </div>
</div>

templates/core/MpesaButton.html
{% load static %}

{% if request.user.is_authenticated %}
<form action="{% url 'stk' %}" method="POST" >
                                                             {% csrf_token %}
                                                             <input type="text" id="phone_number"  hidden  readonly value="0{{user.address.postal_code}}" name="phone_number" placeholder="phone number"
                                                              class="btn form-control" required autofocus    style="font-family:Comic Sans Mn;font-size:24px;text-align:center; margin-top:5px;border-radius:10px;height:7vh; width:100%; "><br>
                                                             <input type="number" id="amount" hidden  readonly value="{{ product.price }}" required name="amount" class=" btn form-control" placeholder="Amount " style="font-family:Comic Sans Mn;font-size:24px;text-align:center; height:7vh;margin-top:20px; margin-bottom:70px;border-radius:10px; width:100%;">
             <button style="border-radius:20px; padding:2px;margin-left:10%;margin-top:80vh;width:60%; " type="submit" class="btn btn-md my-0 p">
              Buy |  <img style="width:50px; font-size:40%;  height:40px;"   src="{% static '/img/mpesa.png'%}">
            </button>
                   </form>

 {% else %}
            <div style="margin-top:50px;" class="text-md lg:flex-grow"></div>
            <div>
                <a href="/Deposit" class="btn mr-2 inline-block font-medium text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-gray-800 hover:bg-white mt-4 lg:mt-0">Buy  | <img style="width:50px; font-size:40%;  height:40px;"   src="{% static '/img/mpesa.png'%}">
                </a></div>
{% endif %}

templates/core/base.html
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
          <link style="border-radius:100%;" rel="shortcut icon" href="{% static 'img/Mboa Academy.jpg '%}"  id="icon" >
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="New Wave of Kenyan trade and investing in digital assets" />
        <meta name="author" content="Mboa Technologies" />
        <title>
            {% block head_title %}MboaEx{% endblock %}
        </title>
      <link rel="stylesheet" href="{% static 'style.css' %}">
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
       <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">

        {% block head_extra %}{% endblock %}
    </head>
     <!-- PG Start -->
   <!-- PG End -->
     <div class="page-loader">
      <div></div>
      <div></div>
      <div></div>
   </div>
   <!-- BG Start -->
   <div class="bg-circles">
      <div class="circle-1"></div>
      <div class="circle-2"></div>
      <div class="circle-3"></div>
      <div class="circle-5"></div>
      <div class="circle-8"></div>
      <div style="background-color:transparent;" class="circle-4"><img style="width:100% ; opacity:13%;  height:100%;border-radius:50%;"   src="{% static 'img/KenyanBrand.jpg'%}" alt="KenyanBrand"></div>

   </div>
   <!-- BG End -->
   <!-- Overlay Start -->
   <div class="overlay"></div>
   <!-- Overlay End -->
    <body class="bg-gray-100">
        {% block body %}

        <div class="main hidden">
         <!-- Header Start -->
         <header class="header">
            <div class="container">
               <div class="row flex-end">
                  <button type="button" class="nav-toggler">
                  <span></span> </button>
                  <div class="nav">
                     <div class="nav-inner">
                         <div style=" font-width:500px bold;color:#008800;margin-left:20px;margin-bottom:10px;" class="about-tabs">
                        <a  href="/accounts/settings" type="button" class="tab-item active ">My Profile</a>
                        <a  href="/ad" type="button" class="tab-item ">About Us</a>
                        <a  href="/biz" type="button" class="tab-item">Matwana</a>
                        <a  href="/transactions/withdraw" type="button" class="tab-item">Discover</a><br>
                         <a  href="/page"  type="button" class="tab-item  "> WhatsApp Groups?</a>
                   {% include 'core/navbar.html' %}
                         </div>

                     </div>

                  </div>
                                    </div>
            </div>
         </header> </div>

         <!-- Header End -->
         <!--Home Section Start -->

            <div class="lg:container lg:mx-auto">
                {% include 'core/messages.html' %}
                {% block content %}
                <!-- Add content here -->
                {% endblock %}
            </div>
            {% include 'core/footer.html' %}

        {% endblock %}
        {% block footer_extra %}{% endblock %}
    </body>
<div class="portfolio-popup">
         <div class="pp-inner">
            <div class="pp-content">
               <div class="pp-header">
                  <button type="button" class="btn pp-close">
                      <i class="fas fa-times"> </i> </button>

                  </div>
                        {% include 'mpesa/LipaNaMpesa.html' %}
               </div>
               <div class="pp-body">
               </div>

            </div>
         </div>

      <!-- Portfolio Item Details Popup Start -->
<script src="{% static 'js/script.js' %}"></script>
</html>

templates/core/blog.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

templates/core/footer.html
{% load static%}
<footer  style="margin-top:30%; " class="footer bg-gray-200 relative pt-1 border-b-2 mt-10">
    <div class="container mx-auto px-6">
<!-- <div class="page-loader">
      <div></div>
      <div></div>
      <div></div>
   <div class="bg-circles">

   </div> -->
        <center>
        <div class="mt-5 flex flex-col items-center">
            <div class="sm:w-2/3 text-center py-6">
                <img style="width:50px; height:50px ; border-radius:50%;margin-bottom:5px; "   src="{%static 'img/Mboa Academy.jpg'%}" alt="Mboa Technology">
                <p class="text-md text-black-900 font-bold mb-2">
                      Mboa Technologies<a href="#" target="_blank">.</a>
                </p>
                              <a  style=" width:100%; padding:2%; position:center;" class="bty" href="/Deposit" ><h4>Support</h4></a>
            </div>
        </div>
        </center>
    </div>
</footer>

templates/core/messages.html
{% for message in messages %}
<div  class="bty bg-teal-100 border-t-4 border-teal-500 rounded-b text-teal-900 px-4 py-3 shadow-md mt-2" style="margin-top:10px; margin-bottom:5%; width:75%;height:20vh; background-color:#001100;"  role="alert">
           <div class="flex">
            <p style="color:#1CA926;" class="font-bold">Success!</p>
            <p style="color:#f6f4f0;" class="text-sm block sm:inline">{{ message }}</p>
        </div>

</div>
    {% endfor %}

templates/core/navbar.html
{% load static %}
<nav style="margin-left:40px margin-bottom:4px;" class="flex items-center justify-between flex-wrap bg-gray-800 p-6">
    <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
        <img style="width:80% ; margin-top:-10%;opacity:100%;  height:50%;border-radius:50%;"   src="{% static 'img/shootCenterBanner.png'%}" alt="KenyanBrand">
        {% if request.user.is_authenticated %}
            <div style=" margin-top:-80%; margin-bottom:2px;" class=" text-md lg:flex-grow">
                <div style="" class="about-tabs">
                        <a  href="/ad" type="button" class="tab-item active ">Available Gigs</a>
                        <a  href="/transactions/deposit" type="button" class="tab-item ">Deposit</a>
                        <a  href="/wallet" type="button" class="tab-item">Wallet</a>
                        <a  href="/setting" type="button" class="tab-item">settings</a>
                        <a  href="/P2P" type="button" class="tab-item">P2P</a>
                        <a  href="/Swap" type="button" class="tab-item ">Swap Funds</a>
                        <a  href="/checkout" type="button" class="tab-item ">CheckOut</a>
                </div>
                <a  style=" background-color:#000;color:#f6f4f1;" href="{% url 'transactions:transaction_report' %}" class=" bty block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                    History
                </a>
                <a style="background-color:#008800;" href="{% url 'transactions:deposit_money' %}" class=" bty block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                    Deposit
                </a>
                <br>
                <a  style="background-color:#062C30;" href="{% url 'transactions:withdraw_money' %}" class="bty block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white">
                    Withdraw
                </a>
                <a href="{% url 'transactions:eshopcart' %}" class="bty block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white">
                    Mboapay
                </a>
<br>
                <a  style="background-color:red;" href="/accounts/logout/" class=" bty inline-block font-medium text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-gray-800 hover:bg-white mt-4 lg:mt-0">Logout</a>

            </div>

        {% else %}
            <div style="margin-top:-10px;" class="text-md lg:flex-grow"></div>
            <div>
                <a href="{% url 'accounts:user_login' %}" class="btn mr-2 inline-block font-medium text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-gray-800 hover:bg-white mt-4 lg:mt-0">Login</a>
            </div>
            <div>
                <a href="{% url 'accounts:user_registration' %}" class="bty inline-block font-medium text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-gray-800 hover:bg-white mt-4 lg:mt-0">Register</a>
            </div>

        {% endif %}
    </div>
      <a href="{% url 'transactions:eshopcart' %}" type="button" class="btn  view-project-btn  block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white">Invest In Mboa Technologies</a> <br>
      <button  style= " margin-top:10px; color:#f6f4f0; background-color:#000;" type="button" class="btn  view-project-btn  block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white">Buy NFTs</button>
    <button   style= " margin-top:5px; color:#008800; background-color:#fff;"  class="btn  view-project-btn  block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white"> <a  style= " color:#008800;" href="/biz"> Visit Wooza Shop</a></button>
</nav>

templates/core/template.html
{% extends 'core/base.html' %}
{% block head_title %}{{ title }}{% endblock %}

{% block content %}
{%load static%}

<section class="home-section align-items-center" id="home">
            <div class="container">
               <div class="row align-items-center">
                  <div class="home-text">
                     <img  class="logo" src="{% static 'img/Mboa Academy.jpg '%}" alt="profile-img">
                     <h1  >  Mboa-ID</h1>








                  </div>
               </div>

                <center>
                        <div  class="btn">
                         <a style=" color:green;" href="/accounts/register" > Get Started - Your MboaID</a>

                   </div>


 </center>
            </div>
    </section>
<section class="home-section align-items-center" id ="support">
    <div class="container">
               <div class="row align-items-center">
                  <div class="home-text">
               <div style="width:20vw; height:25%;margin-top:20px;" class="home-img">

<center>
                   <img style="padding:20%; width:100%; height:50%;" class="logoKenya"   src="{% static 'img/KenyanBrand.jpg'%}" alt="profile-img">

</center>
               </div>
                 <p style="margin-top:40px;">Invest You Money In Mboa Technologies by buying <br>Mboa Coins</p>
                 <a  style=" width:100%; padding:20%; position:center;" class="bty" href="/Deposit" ><h1>Support</h1></a>
                  </div>
               </div>
    </div>
</section>





     {% endblock %}
